# Generated by Django 3.1.1 on 2020-10-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201014_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
