# Generated by Django 3.1.3 on 2021-03-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
