services:
  #web is a service name (can type what u want)
  web:
    build: .
    volumes:
      - .:/blog
    ports:
      - "8000:8000"
      - "9200:9200"
    command: bash -c "
      ls &&
      cd BlogAPI &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate --database=users_db &&
      python3 manage.py migrate &&
      service rabbitmq-server start &&
      service rabbitmq-server status &&

      python3 manage.py runserver 0.0.0.0:8000"