# Generated by Django 3.1.1 on 2020-09-15 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_userpostrelation_reacted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='who_liked',
            field=models.ManyToManyField(related_name='who_liked', through='posts.UserPostRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
