# Generated by Django 3.1.1 on 2020-10-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_postimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='who_liked',
        ),
        migrations.RemoveField(
            model_name='userpostrelation',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userpostrelation',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='UserPostRelation',
        ),
    ]
